[features]
seeds = false
[programs.devnet]
programs = "2yfrDM4QXVRZmQJGfDaWJAUunZjrkZJB1TZi5ZVRBDLT"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/maverick_coder/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
